Miner Registry #11
francisypl/mineranker pull request #13
Opened 2017-03-20 22:49 UTC by abdulbasitkay

Implemented GET, POST and PATCH endpoints for `Miner`

2017-03-20 23:48 UTC, francisypl requested changes

2017-03-20 23:48 UTC, francisypl commented on api/controllers/miners.js
> +        options.q = req.query.q;
I don't think mongo has a q options for `LIKE`.
You probably have to implement something like [this](http://stackoverflow.com/questions/3305561/how-to-query-mongodb-with-like).

2017-03-20 23:48 UTC, francisypl commented on api/swagger/swagger.yaml
> +            $ref: "#/definitions/Miner"
The only required field in the patch body is `description`

2017-03-20 23:48 UTC, francisypl commented on api/models/miner.js
> +        // if not then set those fields to null
This comment is not accurate here

2017-03-20 23:48 UTC, francisypl commented
#11 reference

2017-03-21 08:25 UTC, abdulbasitkay commented on api/swagger/swagger.yaml
> +            $ref: "#/definitions/Miner"
would `type: String` work instead of schema?

2017-03-21 08:26 UTC, abdulbasitkay commented on api/models/miner.js
> +        // if not then set those fields to null
I think we can do without this function.

2017-03-21 08:27 UTC, abdulbasitkay commented on api/controllers/miners.js
> +        options.q = req.query.q;
Okay, would check and update

2017-03-21 17:31 UTC, francisypl commented on api/swagger/swagger.yaml
> +            $ref: "#/definitions/Miner"
Probably should be:
```
type: object
required:
    - description
properties:
    description:
        type: string
```

2017-03-26 02:33 UTC, abdulbasitkay commented on api/controllers/miners.js
> +        query = {name : req.query.q};
having trouble implementing like here. Need help

2017-04-04 22:47 UTC, merged